#!/bin/bash

# Copyright (c) 2020 SpaceWorks developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

NAME=SPACE

CLI=${KOMODOCLI:-./komodo-cli}
$CLI -ac_name=$NAME "$@"
