#!/bin/bash
# Copyright (c) 2022 VaporumCoin developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

NAME=tSPACE

CLI=${KOMODOCLI:-./komodo-cli}
$CLI -ac_name=$NAME "$@"
