#!/bin/bash
# Copyright (c) 2020 SpaceWorks developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR

NAME=tSPACE

# Chain parameters
SUPPLY=3939393
REWARD=3600000000
ADDNODE1=165.227.35.158

KMD=${KOMODOD:-./komodod}
$KMD -ac_name=$NAME                              \
     -ac_supply=$SUPPLY                          \
     -ac_reward=$REWARD                          \
     -ac_cc=939                                  \
     -ac_sapling=1                               \
     -addnode=$ADDNODE1 "$@"
