#!/bin/bash
# Copyright (c) 2022 VaporumCoin developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR

NAME=tSPACE

# Chain parameters
SUPPLY=3939393
ADDNODE1=165.227.35.158
ADDNODE2=165.22.64.156
ADDNODE3=188.166.221.247

KMD=${KOMODOD:-./komodod}
$KMD -ac_name=$NAME                              \
     -ac_supply=$SUPPLY                          \
     -ac_cc=939                                  \
     -ac_sapling=1                               \
     -addnode=$ADDNODE1                          \
     -addnode=$ADDNODE2                          \
     -addnode=$ADDNODE3 "$@"
