#!/bin/bash

# Copyright (c) 2022 vaporum developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR

NAME=VPRM

# Chain parameters
ERAS=6
BLOCKTIME=30
SUPPLY=0
REWARD=5000000000,2500000000,1250000000,625000000,312500000,156250000
END=1000000,3500000,8500000,18500000,38500000,166500000
ADDNODE1=68.3.67.21
ADDNODE2=157.230.90.81
ADDNODE3=167.172.130.118
ADDNODE4=68.3.67.21

KMD=${KOMODOD:-./komodod}
$KMD -ac_name=$NAME                              \
     -ac_supply=$SUPPLY                          \
     -ac_eras=$ERAS                              \
     -ac_reward=$REWARD                          \
     -ac_end=$END                                \
     -ac_blocktime=$BLOCKTIME                    \
     -ac_staked=50                               \
     -ac_cbmaturity=1                            \
     -ac_cc=0                                    \
     -ac_sapling=1                               \
     -addnode=$ADDNODE1                          \
     -addnode=$ADDNODE2                          \
     -addnode=$ADDNODE3                          \
     -addnode=$ADDNODE4 "$@"
