#!/bin/bash

# Copyright (c) 2022 vaporum developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

NAME=VPRM

CLI=${KOMODOCLI:-./komodo-cli}
$CLI -ac_name=$NAME "$@"
